name: C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_DEFAULT_TRIPLET: x64-linux
  VCPKG_DEFAULT_HOST_TRIPLET: x64-linux

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04

    steps:
      - name: Show C++ version
        run: /usr/bin/c++ --version

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeversion: "~3.31.0"

      - name: Setup vcpkg (no install yet)
        uses: lukka/run-vcpkg@v11

      - name: Copy test input files
        run: |
          mkdir -p build/ci/sample_inputs
          cp sample_inputs/input.yml build/ci/sample_inputs/
      

      - name: List files for debugging
        run: |
          pwd
          ls -al
          ls -al ${{ github.workspace }}

      - name: Configure, Build, and Test using Presets
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ci"
          configurePresetAdditionalArgs: "[]"
          buildPreset: "ci-release"
          buildPresetAdditionalArgs: "[]"
          testPreset: "ci-release"
          testPresetAdditionalArgs: "[]"

      - name: Upload CTest log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: LastTest-log
          path: ${{ github.workspace }}/build/ci/Testing/Temporary/LastTest.log
