name: C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_DEFAULT_TRIPLET: x64-linux
  VCPKG_DEFAULT_HOST_TRIPLET: x64-linux

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04

    steps:
      - name: Show C++ version
        run: /usr/bin/c++ --version

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg (no install yet)
        uses: lukka/run-vcpkg@v11

      - name: Configure, Build, and Test using Presets
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci'
          configurePresetAdditionalArgs: "[]"
          buildPreset: 'ci-release'
          buildPresetAdditionalArgs: "[]"
          testPreset: 'ci-release'
          testPresetAdditionalArgs: "[]"
