name: C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_TRIPLET: x64-linux

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04

    steps:
      - name: Show C++ version
        run: /usr/bin/c++ --version

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure with CMake Preset (ci)
        run: cmake --preset ci

      - name: Build (Release)
        run: cmake --build --preset ci-release

      - name: Test (Release)
        run: ctest --preset ci-release

      # Optional: enable this when clang-tidy checks are ready
      # - name: Install clang-tidy
      #   run: sudo apt-get update && sudo apt-get install -y clang-tidy
      #
      # - name: Run clang-tidy
      #   run: |
      #     find src tests -type f \( -name '*.cpp' -o -name '*.h' \) -print0 | xargs -0 clang-tidy -p build/ci

  # Optional code formatting job
  # format:
  #   name: Code Formatting
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3
  #
  #     - name: Install clang-format
  #       run: sudo apt-get update && sudo apt-get install -y clang-format
  #
  #     - name: Run clang-format
  #       run: |
  #         find src tests -type f \( -name '*.cpp' -o -name '*.h' \) -print0 | xargs -0 clang-format -i --style=file
  #         git diff --exit-code
